import './globals.css'
import { NextAuthProvider } from './providers'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import { headers } from 'next/headers'

export const metadata = {
  title: 'Teddies Vs Monsters E-Commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const headersList = headers()
  const referer = headersList.get('referer')

  return (
    <html lang="en">
      <body className='font-body'>
        <NextAuthProvider>
          <Header referer={referer} />
          <main className="pt-[80px] lg:pt-[120px]">
            {children}
          </main>
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  )
}
