
function TableOfContact() {
  return (
    <div className='text-xs w-full h-full flex justify-start flex-col py-6 px-10 leading-[150%]'>

    <p className='pb-3'>
    TABLE OF CONTENTS
    </p>

<p>
1. WHAT INFORMATION DO WE COLLECT?
</p>
<p>
2. HOW DO WE PROCESS YOUR INFORMATION?
</p>
<p>
3. WHAT LEGAL BASES DO WE RELY ON TO PROCESS YOUR PERSONAL INFORMATION?
</p>
<p>
4. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?
</p>
<p>
5. WHAT IS OUR STANCE ON THIRD-PARTY WEBSITES?
</p>
<p>
6. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?
</p>
<p>
7. HOW DO WE HANDLE YOUR SOCIAL LOGINS?
</p>
<p>
8. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?
</p>
<p>
9. HOW LONG DO WE KEEP YOUR INFORMATION?
</p>
<p>
10. HOW DO WE KEEP YOUR INFORMATION SAFE?
</p>
<p>
11. DO WE COLLECT INFORMATION FROM MINORS?
</p>
<p>
12. WHAT ARE YOUR PRIVACY RIGHTS?
</p>
<p>
13. CONTROLS FOR DO-NOT-TRACK FEATURES
</p>
<p>
14. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?
</p>
<p>
15. DO VIRGINIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?
</p>
<p>
16. DO WE MAKE UPDATES TO THIS NOTICE?
</p>
<p>
17. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?
</p>
<p>
18. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?
</p>
    </div>
  )
}

export default TableOfContact